stages:
 - build
  
workflow:
 rules:
  - if: '$CI_COMMIT_BRANCH == "master"'
  
build:
 image: registry.internal.st/dual-universe/dubuild:latest
 stage: build
 variables:
  GIT_SUBMODULE_STRATEGY: recursive
 script:
  - dotnet /app/DUBuild.dll build -s /$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME -o /output -c /$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Config/dubuild.json
 artifacts:
    paths:
      - /output/