stages:
 - build
  
workflow:
 rules:
  - if: '$CI_COMMIT_BRANCH == "master"'
  
build:
 image: registry.internal.st/dual-universe/dubuild:latest
 stage: build
 variables:
  GIT_SUBMODULE_STRATEGY: recursive
 script:
  - dotnet /app/DUBuild.dll build -s /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME -o /output -c /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/Config/dubuild.json -f $CI_PROJECT_NAME.json
 artifacts:
    paths:
      - /output/*.json